# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'Player' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Player
	pod 'MJRefresh', '~> 2.2.1'

end
